services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"   # Redis default port
      - "8001:8001"   # Redis Stack API port (for RedisInsight and other tools)
    environment:
      - REDIS_ARGS=--requirepass mypassword  # Set Redis password
    networks:
      - internal-network
    volumes:
      - ./redis-data:/data  # Persist Redis data

  go-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8081:8081"  # Map the application's port
    networks:
      - internal-network
      - external-network
    depends_on:
      - redis-stack
      - postgres

  ping-authorize-pap:
    image: pingidentity/pingauthorizepap:edge
    container_name: ping-authorize-pap
    ports:
      - "7443:1443"
    environment:
     - PING_EXTERNAL_BASE_URL=localhost:7443
     - LICENSE_DIR=/config
     - LICENSE_FILE_NAME=pingauthorize.lic 
     - PING_IDENTITY_ACCEPT_EULA=YES
     - TAIL_LOG_FILES=/logs/access.log
     - DECISION_POINT_SHARED_SECRET=2FederateM0re
     - PING_OPTIONS_FILE=/opt/server-profile/instance/custom-options.yml 
     - KEYSTORE_FILE=/config/certs/pap.jks
     - KEYSTORE_TYPE=JKS
     - KEYSTORE_PIN_FILE=/config/certs/passwords.txt
     - CERTIFICATE_NICKNAME=pap
    #  - PING_CLIENT_ID=ac_client
    #  - PING_OIDC_CONFIGURATION_ENDPOINT=https://localhost:9031/.well-known/openid-configuration
    #  - PING_SCOPE=oidc email profile phone
    #  - ADDITIONAL_SETUP_ARGS="--enableSelfGovernance"
    #  - PING_OIDC_TLS_VALIDATION=NONE
    volumes:
      - ./config:/config
      - ./pap/server-profile:/opt/server-profile/instance
    networks:
      - external-network
      - internal-network

  ld-sidecar:
    # Option A: Build from the local Dockerfile if code is in ./ld-sidecar
    build:
      context: ./launchdarkly
      dockerfile: Dockerfile
    container_name: ld-sidecar

    # Expose an external port if you want to test from outside:
    ports:
      - "8082:8081"
    environment:
      - LAUNCHDARKLY_SDKKEY=sdk-0b9b2fb6-e74e-46f8-8a75-eab8a0e9055f
      - LAUNCHDARKLY_APPID=demo-app
      - LAUNCHDARKLY_VERSION=1.0.0
      - SERVER_PORT=8081
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_EXAMPLE=DEBUG
      - LAUNCHDARKLY_LOGLEVEL=INFO

    networks:
      - internal-network
    depends_on:
      - ping-authorize


  ping-authorize:
    image: pingidentity/pingauthorize:edge
    container_name: authZEN-pdp
    volumes:
      - /run/secrets                          # Mount tmpfs directory for secrets
      - ./option-cache:/opt/logs/option-cache # Mount option-cache directory
      - ./config:/config
      - ./config/pd.profile:/opt/staging/pd.profile
      - ./webapps/console.war:/opt/in/instance/webapps/console.war
    tmpfs:
      - /run/secrets:rw,nosuid,nodev,noexec,mode=0777  # Set tmpfs with write permissions
    ports:
      - "1389:1389"
      - "1636:1636"                          # Map the LDAP port
      - "8443:1443"                          # Map the HTTPS port
    environment:
      - LICENSE_DIR=/config
      - INSTANCE_ID=sd1-task1
      - PING_IDENTITY_ACCEPT_EULA=YES
      - LICENSE_FILE_NAME=pingauthorize.lic
      - PING_INSTANCE_NAME=authZEN
      - JSON_API_HEADER_NAME=client
      - PDP_SHARED_SECRET=2FederateM0re
      - SIDEBAND_SECRET_HEADER_NAME=CLIENT_TOKEN
      - SIDEBAND_SHARED_SECRET=2FederateM0re
      - SIDEBAND_SERVICE=AuthZEN
      - POLICY_NODE_ID=6ae6edd5-0283-4ec8-ac84-08df56df1f63
      - DEPLOYMENT_PACKAGE</opt/staging/pd.profile/Deployment-Package-cf45b188-2d1c-4bde-ab37-6c3dab34ab80.deploymentpackage
      - POLICY_BRANCH=AuthZen
    networks:
      - external-network
      - internal-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - internal-network
    command: bash -c "rm -rf /var/lib/postgresql/data/* && docker-entrypoint.sh postgres"


  kong:
    build:
      context: ./kong-ping-auth-setup
      dockerfile: Dockerfile
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: kong
      KONG_LOG_LEVEL: debug
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_PLUGINS: bundled,ping-auth
    ports:
      - "8000:8000"  # Proxy
      - "9443:8443"  # Proxy SSL
      - "8002:8001"  # Admin
      - "8444:8444"  # Admin SSL
    depends_on:
      - postgres
      - ping-authorize
    volumes:
      - ./kong/scripts:/kong-scripts
    entrypoint: >
      /bin/sh -c "
        kong migrations bootstrap && 
        kong start && 
        sleep 5 && 
        /kong-scripts/configure-kong.sh &&
        tail -f /dev/null
      "
    networks:
      - external-network
      - internal-network


volumes:
  kong-db-data:
    
networks:
  internal-network:
    driver: bridge # Internal services will communicate here
  external-network:
    driver: bridge # Only mtls is exposed externally
